version: "3"
services:
  app:
    image: php:8.0-apache
    volumes:
      - ./:/var/www
      - ./public:/var/www/html
#    environment:
#      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - 8080:80